### PR TITLE
respect sorting selection in query table view

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by andrewseguin** [comment]
The `Group By` shows up in the display options, it would make sense to hide that if no grouper is provided

**Comment by andrewseguin** [comment]
lol clearly Im reviewing in the wrong order =D https://github.com/crafted/crafted/pull/67

**Comment by andrewseguin** [comment]
You should be also able to remove the following from the styling:

```css

button.mat-menu-item {
  mat-icon {
    visibility: hidden;
  }

  &.selected {
    font-weight: bold;
    mat-icon {
      visibility: visible;
    }
  }
}

.mat-menu-item {
  @include slim-menu-item();
}
```

**Comment by josephperrott** [comment]
Done.

**Pull request merged**
